spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/school_bus?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: long
    password: 214017
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 10
#      min-idle: 5
#      max-active: 20
#      query-timeout: 6000
#      transaction-query-timeout: 6000
#      remove-abandoned-timeout: 1800
#  devtools:
#    restart:
#      enabled: true

  ##页面模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    cache: false
    mode: html
    encoding: utf-8
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: /static/
##mabatis环境配置集成
mybatis:
  #type-aliases-package: xyz.system.jlaubus.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true

  config-location:


logging:
  level:
    com:
      example:
        mapper : debug

server:
  port: 8080



